language: node_js

os:
  - windows
  - linux
  - osx

dist: focal

node_js:
  - 14

install: npm install

script: >-
  echo "const builder=require('electron-builder');if(process.env.TRAVIS_OS_NAME==='osx')builder.build({projectDir:'electron',targets:['macos']});else builder.build({projectDir:'electron',targets:[process.env.TRAVIS_OS_NAME]})" | node
