language: node_js

os:
  - windows
  - linux
  - osx

arch:
  - arm64
  - ppc64le
  - s390x

dist: focal

node_js:
  - 14

install: npm install

script: node --trace-uncaught --trace-warnings --unhandled-rejections=strict .ci/ci.js
